###Criar loja
POST http://localhost:3000/loja
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXJuYW1lIjoibG9qaXN0YTEiLCJyb2xlIjoiTE9KSVNUQSIsImlhdCI6MTc0OTU3NTU4NywiZXhwIjoxNzQ5NTc5MTg3fQ.1_qqKLV8kQUsi923wLeMd_3Ek-3H3WLs_H-vyC5Uf9k

{
  "nome": "Loja do Filipi",
  "telefone": "61982643446",
  "dados_bancarios": "02954349107",
  "usuarioId":2
}


### Atualizar loja
PATCH http://localhost:3000/loja/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXJuYW1lIjoibG9qaXN0YTEiLCJyb2xlIjoiTE9KSVNUQSIsImlhdCI6MTc0OTU3NTU4NywiZXhwIjoxNzQ5NTc5MTg3fQ.1_qqKLV8kQUsi923wLeMd_3Ek-3H3WLs_H-vyC5Uf9k
Content-Type: application/json

{
  "nome": "Loja do Filipi",
  "telefone": "61982643446",
  "dados_bancarios": "9515375653",
  "usuarioId":2
}

### Deletar loja
DELETE http://localhost:3000/loja/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXJuYW1lIjoibG9qaXN0YTEiLCJyb2xlIjoiTE9KSVNUQSIsImlhdCI6MTc0OTU3NTc1MiwiZXhwIjoxNzQ5NTc5MzUyfQ.ojxeC9Lel_AVkRIqEDgtrkLjOHOJyg1Xe3rA_caMTUw

### Criar produto
POST http://localhost:3000/produto
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXJuYW1lIjoibG9qaXN0YTEiLCJyb2xlIjoiTE9KSVNUQSIsImlhdCI6MTc0OTU3NTc1MiwiZXhwIjoxNzQ5NTc5MzUyfQ.ojxeC9Lel_AVkRIqEDgtrkLjOHOJyg1Xe3rA_caMTUw
Content-Type: application/json

{
  "nome": "Teste",
  "descricao":"Teste criar produto",    
  "valor": 999,
  "id_categoria":1,
  "id_loja":1
}

### Atualizar um produto
PATCH http://localhost:3000/produto/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXJuYW1lIjoibG9qaXN0YTEiLCJyb2xlIjoiTE9KSVNUQSIsImlhdCI6MTc0OTU3NTc1MiwiZXhwIjoxNzQ5NTc5MzUyfQ.ojxeC9Lel_AVkRIqEDgtrkLjOHOJyg1Xe3rA_caMTUw
Content-Type: application/json

{
  "nome": "Banana",
  "descricao":"Banana maravilha",    
  "valor": 12,
  "id_categoria":1,
  "id_loja":1
}

### Deletar um produto
DELETE http://localhost:3000/produto/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXJuYW1lIjoibG9qaXN0YTEiLCJyb2xlIjoiTE9KSVNUQSIsImlhdCI6MTc0OTU3NTc1MiwiZXhwIjoxNzQ5NTc5MzUyfQ.ojxeC9Lel_AVkRIqEDgtrkLjOHOJyg1Xe3rA_caMTUw
