### Obter registros
GET http://localhost:3000/auth/register

### Registrar um usuário comum
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "cliente1",
  "senha":"123456",
  "email": "cliente1@teste.com",
  "role": "USER",
  "id_Endereco":1
}

### Fazer login usuario
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username":"cliente1",
  "senha":"123456"
}

### Registrar um entregador
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "entregador1",
  "senha": "123456",
  "email": "entregador1@teste.com",
  "role": "ENTREGADOR"
}

### Fazer login entregador
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "entregador1",
  "senha": "123456"
}

### Registrar um lojista
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "lojista1",
  "senha": "123456",
  "email": "lojista1@teste.com",
  "role": "LOJISTA",
  "id_Endereco":2
}

### Fazer login lojista
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "lojista1",
  "senha": "123456"
}