###Criar loja
POST http://localhost:3000/loja
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXJuYW1lIjoibG9qaXN0YTEiLCJyb2xlIjoiTE9KSVNUQSIsImlhdCI6MTc0OTUyMzE0MiwiZXhwIjoxNzQ5NTI2NzQyfQ.ngk-drtdGpbbSCsgUfpnkFHUy50ZoJntqMe0hwe76tg

{
  "nome": "Loja do Filipi",
  "telefone": "61982643446",
  "dados_bancarios": "02954349107",
  "usuarioId":2
}


### Atualizar loja
PATCH http://localhost:3000/loja/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXJuYW1lIjoibG9qaXN0YTEiLCJyb2xlIjoiTE9KSVNUQSIsImlhdCI6MTc0OTUyMzE0MiwiZXhwIjoxNzQ5NTI2NzQyfQ.ngk-drtdGpbbSCsgUfpnkFHUy50ZoJntqMe0hwe76tg
Content-Type: application/json

{
  "nome": "Loja do Filipi",
  "telefone": "61982643446",
  "dados_bancarios": "9515375653",
  "usuarioId":2
}

### Deletar loja
DELETE http://localhost:3000/loja/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXJuYW1lIjoibG9qaXN0YTEiLCJyb2xlIjoiTE9KSVNUQSIsImlhdCI6MTc0OTUyMzE0MiwiZXhwIjoxNzQ5NTI2NzQyfQ.ngk-drtdGpbbSCsgUfpnkFHUy50ZoJntqMe0hwe76tg

### Criar produto
POST http://localhost:3000/produto
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXJuYW1lIjoibG9qaXN0YTEiLCJyb2xlIjoiTE9KSVNUQSIsImlhdCI6MTc0OTUyMzE0MiwiZXhwIjoxNzQ5NTI2NzQyfQ.ngk-drtdGpbbSCsgUfpnkFHUy50ZoJntqMe0hwe76tg
Content-Type: application/json

{
  "nome": "Teste",
  "descricao":"Teste criar produto",    
  "valor": 999,
  "id_categoria":1,
  "id_loja":1
}

### Atualizar um produto
PATCH http://localhost:3000/produto/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXJuYW1lIjoibG9qaXN0YTEiLCJyb2xlIjoiTE9KSVNUQSIsImlhdCI6MTc0OTUyMzE0MiwiZXhwIjoxNzQ5NTI2NzQyfQ.ngk-drtdGpbbSCsgUfpnkFHUy50ZoJntqMe0hwe76tg
Content-Type: application/json

{
  "nome": "Banana",
  "descricao":"Banana maravilha",    
  "valor": 12,
  "id_categoria":1,
  "id_loja":1
}

### Deletar um produto
DELETE http://localhost:3000/produto/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXJuYW1lIjoibG9qaXN0YTEiLCJyb2xlIjoiTE9KSVNUQSIsImlhdCI6MTc0OTUyMzE0MiwiZXhwIjoxNzQ5NTI2NzQyfQ.ngk-drtdGpbbSCsgUfpnkFHUy50ZoJntqMe0hwe76tg
